import = [
    "~/.config/alacritty/themes/themes/tokyonight_night.toml"
]

[shell]
    program = "/bin/zsh"

[font]
    size = 10
    normal = { family="MesloLGM Nerd Font", style="Regular"}
    bold = { family="MesloLGM Nerd Font", style="Bold"}
    italic = { family="MesloLGM Nerd Font", style="Italic"}
